networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    networks:
      - roboshop
  redis:
    image: redis:v1
    container_name: redis
    networks:
      - roboshop
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - mongodb
    networks:
      - roboshop
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
    networks:
      - roboshop
  web:
    image: web:v1
    command: web
    networks:
      - roboshop
    depends_on:
      - catalogue
      - cart
      - user
    ports:
      - "8080:80"
